services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-password}@db:${DB_PORT:-5432}/${DB_NAME:-personal_finance_app}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-personal_finance_app}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - app_data:/data

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 5173:80
    depends_on:
      - server

volumes:
  app_data:
  redis_data:
