name: Code Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

defaults:
  run:
    shell: bash

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint and format client
        run: |
          cd client
          pnpm lint
          pnpm format:check
      - name: Lint and format server
        run: |
          cd server
          pnpm lint
          pnpm format:check

  unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run unit tests for client
        run: |
          cd client
          pnpm test:unit
      - name: Run unit tests for server
        run: |
          cd server
          pnpm run --if-present test:unit

  e2e_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run e2e tests for client
        run: |
          cd client
          pnpm test:e2e
      - name: Run e2e tests for server
        run: |
          cd server
          pnpm run --if-present test:e2e
