name: Code Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

defaults:
  run:
    shell: bash

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: ./.github/actions/setup-node
      - name: Lint and format client
        run: |
          cd client
          pnpm install
          pnpm lint
          pnpm format:check
      - name: Lint and format server
        run: |
          cd server
          pnpm install
          pnpm lint
          pnpm format:check
